apiVersion: apps/v1
kind: Deployment
metadata:
  name: categoryservice-deployment
  labels:
    app: categoryservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: categoryservice
  template:
    metadata:
      labels:
        app: categoryservice
    spec:
      containers:
      - name: categoryservice
        image: categoryservice:latest 
        imagePullPolicy: Never
        ports:
        - containerPort: 666  
        - containerPort: 7002 
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:666;http://+:7002"

---
apiVersion: v1
kind: Service
metadata:
  name: categoryservice
spec:
  selector:
    app: categoryservice
  ports:
  - name: grpc
    protocol: TCP
    port: 666
    targetPort: 666
  - name: webapi
    protocol: TCP
    port: 7002
    targetPort: 7002
  type: LoadBalancer  # You can use NodePort or ClusterIP for local setups
